### ISSUE TITLE
[BUG] Can't build gtk-demo example

### ISSUE THREAD

**Issue by vuuk** [38/plotters#118]
**Describe the bug**
Cannot build the gtk-demo from the examples.
I get the following compilation error: 

`
 --> src/main.rs:12:38 let root = CairoBackend::new(cr, (500, 500)).unwrap().into_drawing_area();

expected struct `cairo::context::Context`, found a different struct `cairo::context::Context`
   
   
note: expected type `&cairo::context::Context` (struct `cairo::context::Context`)
              found type `&cairo::context::Context` (struct `cairo::context::Context`)

note: Perhaps two different versions of crate `cairo` are being used?

`

**To Reproduce**
Run cargo build on
[`https://github.com/38/plotters/tree/master/examples/gtk-demo`](gtk-demo)

**Comment by 38** [comment]
Hi Evdin,
Thanks for reporting this, this should be fixed on latest master branch. 

If you have any other problem, please let me know. 


Sorry for delayed reply. 

Cheers!
