### ISSUE TITLE
Impossible to control axis ticks w/ logarithmic scale)

### ISSUE THREAD

**Issue by forrestthewoods** [38/plotters#126]
**Describe the bug**
It's very difficult to control axis ticks with a logarithmic scale. Impossible even.

In my example, full code below, `y_labels(20)` produces 21 ticks. If it changes from 20 to 19 then it has... 3 ticks. Something is amiss.

What I _really_ want is the ability to set my ticks explicitly. But in lieu of that I do think it's a little buggy. I flip flopped between filing a bug report for the former and a feature request for the latter. But I didn't want to produce two issues so we'll start here. :)

**Version Information**
`plotters = "0.2.12"`

**To Reproduce**
Observe the call `y_labels(20)`. If this is 20 then the chart has many ticks: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 2000, 3000.

If you change it to `y_label(19)` then it has only 3 ticks: 10, 100, 1000

```
fn min_repro() -> Result<(), Box<dyn std::error::Error>> {
    let root_area = BitMapBackend::new("log_ticks.png", (1024,768)).into_drawing_area();

    root_area.fill(&WHITE)?;

    let root_area = root_area.titled("Bug Repro", ("sans-serif", 60).into_font())?;
    let root_area = root_area.margin(50, 50, 50, 50);
    
    let mut cc = ChartBuilder::on(&root_area)
        .set_all_label_area_size(50)
        .build_ranged(0f32..40f32, LogRange(10f32..3500f32))?;

    cc.configure_mesh()
        .x_labels(10)
        .x_label_formatter(&|v| format!("{:.0}", v))
        .y_labels(20) // CHANGE ME to 19
        .y_label_formatter(&|v| format!("{:.0}", v))
        .disable_mesh()
        .draw()?;

    Ok(())
}
```

**Comment by 38** [comment]
Hi there, I assume this is expected results. The basic semantics Plotters for the ticks hint is the number means the number of ticks Plotters can emit at most. For this particular case, 19 doesn't makes it always gives you 19 values, instead it's up to the coordinate type to decide what to put.

In Plotters 0.3, we are now support manual control of the tick marks https://docs.rs/plotters/0.3.0/plotters/coord/combinators/trait.BindKeyPoints.html#tymethod.with_key_points

I assume this solves your issue, so closing it and feel free to reopen it if anything I was missing.

Thanks!
