### ISSUE TITLE
Release v0.2.13 raises MSRV without raising minor version

### ISSUE THREAD

**Issue by asomers** [38/plotters#140]
plotters release v0.2.12 was compilable with Rust 1.36.0, and probably older versions too.  But version v0.2.13 requires Rust 1.40.0.  That means that downstream crates are suddenly breaking from `cargo update`.  Raising the MSRV should be considered a backwards-incompatible change, because it can break your consumers' builds.

Please commit to maintaining a stable MSRV in the future.  You can easily verify it in CI.

See https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980/30 for discussion.

**Comment by 38** [comment]
Oops, thanks for reporting this. Believe this is fixed with latest release 0.2.14.
Really appreciated about the advice. 
Thanks!
