### ISSUE TITLE
[Feature Request] 3D surface/contour/line plotting?

### ISSUE THREAD

**Issue by estysdesu** [38/plotters#141]
### What is the feature ?
Support for 3D plots (lines, contours, surfaces).

### (Optional) Why this feature is useful and how people would use the feature ?
Many mature plotting libraries provide support for plotting 3D shapes (lines, contours, surfaces). 
* [igiagkiozis/plotly](https://github.com/igiagkiozis/plotly#surface-plot), which is bindings for the plotly.js library, supports 3D lines and surfaces. 
* [siegelord/rustgnuplot](https://github.com/SiegeLord/RustGnuplot#features) supports 3D contours and surfaces. 

Now, I understand these libraries are actually just bindings for plotting libraries written in other languages, but [38/plotters](https://github.com/38/plotters) is the only library (that I have found so far) that natively supports the [EvCxR Jupyter Kernel](https://github.com/google/evcxr/tree/master/evcxr_jupyter). 3D plotting is one thing I think most people expect from a mature plotting library (at least in the data science realm). I'm aware, that 38/plotters is technically a drawing library vs a plotting library. But, even an example of how to generate a 3D plot would be a nice springboard.

Thoughts?

**Comment by 38** [comment]
Hi there, thank for using Plotters. You have already realized that the plotters is more like a drawing library vs plotting library. Unfortunately the low level drawing API only support for 2D drawing and 3D drawing is on my backlog for a long time. 

For the roadmap of the 3D plots, I am going to support CPU 3D rendering first which I am planning to support it after the next major release which is happening in this or next month. For hardware accelerated rendering, it will take a longer time. 

Cheers!

**Comment by 38** [comment]
Supported in v0.3
