### ISSUE TITLE
[BUG] Can't run examples

### ISSUE THREAD

**Issue by davidclevenger** [38/plotters#144]
**Describe the bug**
When running any example (e.g. `cargo run --example boxplot`, etc.), nothing will happen.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/24283448/82365052-b9a67880-99d5-11ea-8034-d1d8c61d0277.png">

**To Reproduce**
Some minimal reproduce code is highly recommended
* Fresh clone of repo
* `cargo build`
* `cargo run --example boxplot`

**Version Information**
Please give us what version you are using. If you are pulling `Plotters` directly from git repo, please mention this as well
* Example built from cloned repo (I guess version is current HEAD of master - https://github.com/38/plotters/commit/b8d115dcf8d0f269de3ebdb56a32b68b5d192895 )
* System: Mac
* OS: OSX Mojave 10.14.6
* Arch: AMD64

**Comment by 38** [comment]
Hi David, thanks for trying plotters. The output file is generated under `plotters-doc-data` directory. You can open the output with your image viewer :)

https://github.com/38/plotters/blob/42dc17dea6d73974b906a8523658db5d6ef11761/examples/boxplot.rs#L25
