### ISSUE TITLE
[Feature Request] support NaiveDate as coord

### ISSUE THREAD

**Issue by TeXitoi** [38/plotters#145]
### What is the feature ?

chrono::Date is supported as coord. It could be great to have chrono::NaiveDate also supported.

I might implement it if you are OK with the feature.

**Comment by 38** [comment]
Thanks for trying Plotters. This is supported with the v0.3 major release and hopefully will be released soon. 

https://github.com/38/plotters/blob/eac00ef1fa6d344a413a5f4b175cd4a81f73a74a/src/coord/datetime.rs#L123

Cheers!
