### ISSUE TITLE
[BUG] canvas stroke width

### ISSUE THREAD

**Issue by jangernert** [38/plotters#166]
**Describe the bug**

@jbowens in #39 
> I'm having trouble setting a stroke width as well. Does the wasm/canvas backend support setting a stroke width? That's the backend that I've been trying.

I'm facing the same issue. So I'm opening it as a new issue for visibility. I'm also using wasm/canvas and set the line to something ridiculous like 20. Still no visible change in line thickness.

**To Reproduce**
```
let backend = CanvasBackend::new("canvas").unwrap();
let root = backend.into_drawing_area();

root.fill(&WHITE).unwrap();

let mut chart = ChartBuilder::on(&root)
    .set_left_and_bottom_label_area_size(30)
    .margin(10)
    .build_ranged(0.0..2.0, 0.0..3.0)
    .unwrap();

chart
    .configure_mesh()
    .x_labels(3)
    .y_labels(2)
    .draw()
    .unwrap();

let data = (0..=20)
    .map(|x| x as f64 / 10.0)
    .map(|x| (x, x.powf(2.0) + 1.0));

chart.draw_series(
    AreaSeries::new(
        data.clone(),
        0.0,
        &RED.mix(0.2),
    )
    .border_style(Into::<ShapeStyle>::into(&RED).stroke_width(20)),
).unwrap();

chart.draw_series(
    data
        .map(|(x, y)| Circle::new((x, y), 3, BLUE.filled())),
).unwrap();

root.present().unwrap();
```

**Version Information**
```
plotters = "0.2"
```

**Comment by jangernert** [comment]
I see this one already has a fix waiting to be merged: https://github.com/38/plotters/pull/156

**Comment by 38** [comment]
Fixed in latest release

**Comment by jbowens** [comment]
Thanks, @38!

**Comment by ensonmj** [comment]
plotters 0.3,
does anyone make stoke width work？
I clone this repo，and try to change style `let style = Into::<ShapeStyle>::into(&BLUE).stroke_width(100).filled();` 
but nothing changed
