### ISSUE TITLE
Draw horizontal lines in a ChartContext?

### ISSUE THREAD

**Issue by kangalioo** [38/plotters#168]
Hello,

is it possible to draw colored horizontal lines in a ChartContext? Like the horizontal lines in the image
![image](https://user-images.githubusercontent.com/21220820/88036731-3f64b280-cb44-11ea-85a9-9c1ca81b7e93.png)

I tried using a PathElement with a single edge, however it seems like you can only draw the path element onto a DrawingArea, not onto a ChartContext.

I also had the idea to configure the mesh so that I can arbitrarily define the horizontal mesh lines' positions and colors. MeshStyle doesn't seem to give that kind of precise control though.

**Comment by benruijl** [comment]
You can draw a new series for each horizontal line:
```rust
     let hori = (0..2).map(|i| ( i as f32, 0.2));

    chart.draw_series(LineSeries::new(
        hori,
        &BLACK,
    ))?;
```

**Comment by 38** [comment]
Hi thanks for trying plotters - and sorry for the huge delay on this reply 

You probably want [this method](https://docs.rs/plotters/0.2.15/plotters/chart/struct.ChartContext.html#method.plotting_area).

Also the grid line styles, I am going to work on this for the next major release!

Cheers
