### ISSUE TITLE
Please add support for chrono NaiveDate

### ISSUE THREAD

**Issue by jgoerzen** [38/plotters#173]
### What is the feature ?

The chrono crate provides a NaiveDate, which is a date without an associated timezone.  This is often useful in date-based data processing and should be pretty easy to support here.  It would be great to have appropriate impls so that NaiveDates can be used directly.

**Comment by 38** [comment]
Hi there, thanks for using Plotters! 

NaiveDate is going to be supported with unreleased next major release which I am planning to release for a while. 
At this time, you should be able to try the next release from the [v0.3-pre branch of this repo](https://github.com/38/plotters/tree/v0.3-pre)

**Comment by 38** [comment]
As long as this is already supported in v0.3 development branch, closing the issue
