### ISSUE TITLE
[BUG] Clicking the WASM link in the README leads to a warning page

### ISSUE THREAD

**Issue by AlexDikelsky** [38/plotters#175]
![warning_page](https://user-images.githubusercontent.com/52082790/90057722-6bd4a000-dca6-11ea-9d46-4549249ccce9.PNG)

**Describe the bug**
When I click the link in the readme in the third bullet at the top ("To view the WASM example, go to this link"), it leads to a warning page.

**To Reproduce**
Open specified link

**Version Information**
On git repo README (8/12/2020)

Otherwise, the library has been useful!

**Comment by 38** [comment]
Thanks for reporting this, fixed the issue problem!
