### ISSUE TITLE
Where is plotters-backend hosted

### ISSUE THREAD

**Issue by chrisduerr** [38/plotters#184]
The Repository URL at https://crates.io/crates/plotters-backend is incorrect.

**Comment by 38** [comment]
Hi, I checked the crates.io, the repository link seems right. 

https://github.com/plotters-rs/plotters-backend.

**Comment by chrisduerr** [comment]
https://github.com/plotters-rs/plotters-backend/blob/master/Cargo.toml#L3 is it right?

**Comment by 38** [comment]
> https://github.com/plotters-rs/plotters-backend/blob/master/Cargo.toml#L3 is it right?

Oops, I should push the local commit. Just fixed, thanks a lot
