### ISSUE TITLE
Add palette color support

### ISSUE THREAD

**Issue by Veykril** [38/plotters#19]
I just thought it might be of interest to start a discussion about this. I noticed this crate uses it's own simplistic color definitions, so to my mind came the possibility of using the [palette crate](https://github.com/Ogeon/palette) which would allow users to define and use colors in a very great spectrum.

**Comment by 38** [comment]
Yes, that looks awesome. Thank you for this suggestion.

**Comment by Veykril** [comment]
I wouldn't mind making a PR for this as well then.

**Comment by 38** [comment]
That would be fantastic! thank you in advance!
