### ISSUE TITLE
Plotting y=1/x and y=x.sqrt.

### ISSUE THREAD

**Issue by Roge-semenov** [38/plotters#198]
I really liked the Plotters graphics library, using it is very easy and fast to build graphs. But I don't know how to plot y=1/x and y=x.sqrt  in the coordinate system. There are nothing about it in the examples. Could you explain to me how to do this?

**Comment by arctic-alpaca** [comment]
There is actually an example in the [readme](https://github.com/38/plotters#quick-start) for y=x^2 .

**Comment by Roge-semenov** [comment]
Thank you very much, but my graph looks very strange. How to make it located in 2 coordinate planes and displayed on a larger scale? 
Here is my code 
```rust
use plotters::prelude::*;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = BitMapBackend::new("images/123.png", (640, 480)).into_drawing_area();
    root.fill(&WHITE)?;
    let mut chart = ChartBuilder::on(&root)
        .caption("y=1/x", ("sans-serif", 50).into_font())
        .margin(5)
        .x_label_area_size(30)
        .y_label_area_size(30)
        .build_cartesian_2d(-1f32..1f32, -0.1f32..1f32)?;

    chart.configure_mesh().draw()?;

    chart
        .draw_series(LineSeries::new(
            (-50..=50).map(|x| x as f32 / 50.0).map(|x| (x, 1.0/x)),
            &RED,
        ))?
        .label("y = 1/x")
        .legend(|(x, y)| PathElement::new(vec![(x, y), (x + 20, y)], &RED));

    chart
        .configure_series_labels()
        .background_style(&WHITE.mix(0.8))
        .border_style(&BLACK)
        .draw()?;

    Ok(())
}```
And it makes:
![image](https://user-images.githubusercontent.com/73400206/97276825-c4005480-1848-11eb-995c-34e16ee1c07c.png)
I want the graph to display something like this:
![image](https://user-images.githubusercontent.com/73400206/97277154-2e18f980-1849-11eb-848d-9c80d390af8f.png)

**Comment by arctic-alpaca** [comment]
All the values in the interval you are displaying are bigger than 1 or smaller than -1 for 1/x. But I'm not sure why plotters is displaying it at all then, it's probably up to the user to make sure the values fit inside the coordinate system. The line in the middle is plotters connecting all datapoints it has. I'm not sure if plotters supports functions with "jumps" like this.

`(-50..=50).map(|x| x as f32 / 50.0).map(|x| (x, 1.0/x))` generates 100 datapoints from x = -50/50 to x = 50/50. To generate datapoints outside of -1<=x<=1 you need to adapt this part. To generate datapoints between -2 and 2 you can use `(-50..=50).map(|x| x as f32 / 25.0).map(|x| (x, 1.0/x))`

To change the coordinate system, you can modify [`build_cartesian_2d`](https://docs.rs/plotters/0.3.0/plotters/chart/struct.ChartBuilder.html#method.build_cartesian_2d) to fit your needs.

**Comment by Roge-semenov** [comment]
Thank you very much, everything worked as I wanted.
