### ISSUE TITLE
can't begin my work on windows 10 

### ISSUE THREAD

**Issue by adsick** [38/plotters#213]
I added plotters dependency, copied the sample project code with y = x^2, compiled with cargo run
there was no errors, but plot didn't show up. Then I decided to run the executable itself and saw, that just some console window appears for 1-3 frames and then it disappears, that's it...(

I use all stable Rust

**Describe the bug**
Describe what is expected, what you actually get.
It would be nice to have screenshot or result image uploaded  

**To Reproduce**
Some minimal reproduce code is highly recommended

**Version Information**
Please give us what version you are using. If you are pulling `Plotters` directly from git repo, please mention this as well

**Comment by adsick** [comment]
It was not clear that not every example Is supposed to open some windows with content in them.
It is not obvious from the Quick start, that crate actually generates images.

**Comment by Kuzirashi** [comment]
Yes, it looks like that in quick start example by default it saves the produced result into a file that you pass in BitMapBackend::new.
