### ISSUE TITLE
Plotters does not work. Mac OS Big Sur. Do I need to install some additional software?

### ISSUE THREAD

**Issue by zzeee** [38/plotters#232]
I've cloned the main repository. 
Doing commands:
cd examples
 cargo run --example stock  
and see only
Compiling plotters v0.3.0 (/Users/andrejzienko/prj/plotters)
    Finished dev [unoptimized + debuginfo] target(s) in 2.03s
     Running `/Users/andrejzienko/prj/plotters/target/debug/examples/3d-plot`
    but NOTHING is happening.
no windows - nothing
Mac Os Big Sur
the single example which works is console. What should I do to launch an example?

**Comment by attila-kun** [comment]
Examples are generated under the `plotters-doc-data` folder. Does that help?

**Comment by chuong** [comment]
As a new user, I had the same confusion and unnecessarily spoiled experience to this wonderful library.
Please add the clarification to `examples/README.md`

**Comment by 38** [comment]
Thanks for reporting is. Closing it since it's related to issue #236, I am planning to come up with a tweak-able drop behavior which should be able to address this issue.
