### ISSUE TITLE
[BUG] Silent Failure When Output Directory Does not Exist

### ISSUE THREAD

**Issue by theduke** [38/plotters#236]
**Describe the bug**

When writing a chart  to a directory that does not exist (with `ctx.draw_series()` or similar)  `Result::Ok` is returned, but not image file is written.

It starts working after creating the output directory manually.

The operation should either fail, or automatically create the directory.

**Version Information**

`plotters 0.3.0`

**Comment by 38** [comment]
Hi there, thanks for reporting the issue. Apologize for delayed reply.

I understand it's really confusing and feel we need at least do something to improve the experience.  Actually, this issue has a long history. 

Plotters uses the `Drop` to finalize the plotting. Originally, the `drop` implementation panics when it's not possible to finalize the plotting. But this causing some other problems (see issue #99) and silently ignore the failure is the way how Rust standard library handle it. 

But it's really confusing, especially when people not realize the behavior is ignore the failure. 

> The operation should either fail, or automatically create the directory.

I think this is a good idea, but I don't want this to be the default behavior. So one possible solution I think is we can allow user to specify the behavior of `drop`. 

Please let me know if you have any thoughts.

Cheers!
