### ISSUE TITLE
[BUG] Link for piston-demo is dead

### ISSUE THREAD

**Issue by AP2008** [38/plotters#238]
The link for the piston-demo is dead.   
https://github.com/38/plotters/tree/master/examples/piston-demo
![Screenshot_20210318_070922](https://user-images.githubusercontent.com/44343120/111560661-f3dcd400-87b8-11eb-8804-3ffe37e31b0a.png)
Where is the code for the live CPU plot example?

**Comment by 38** [comment]
Thanks for reporting this. Got link fixed on master branch!
