### ISSUE TITLE
x_labels(0) creates one point

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [38/plotters#24]
In [this example](https://github.com/38/plotters/blob/master/examples/chart.rs), if I change `x_labels(5)` to `x_labels(0)`, the labels don't go away. The latter is basically equivalent to `x_labels(1)`. I want to be able to remove the labels to achieve something like [this](https://stackoverflow.com/questions/31810461/python-matplotlib-vertically-aligned-plots-in-matplotlib) and [this](https://stackoverflow.com/questions/38107451/python-matplotlib-suptitle-with-arbitrary-number-of-vertical-figures).

**Comment by TheQuantumPhysicist** [comment]
I found a trick to achieve this, which is by using `x_label_offset(1000000)`... a dumb solution, I know. But it works until this bug is fixed.

**Comment by 38** [comment]
Hi,
I am happy to know you find this helpful! And sorry for delayed reply!

And yes, you should work around in that way. I look into the code, it seems this is a bug. 

I am going to fix this and I will let you know if a new version with the fix released!

Thanks again,
Hao

**Comment by 38** [comment]
Hi,

I made the fix to this bug. Now you should be able to use `x_labels(0)` to avoid it creates any labels with version `0.2.5`.

Please let me know if it works on your side. 

Closing this issue, feel free to reopen it if you feel anything is still wrong.

Cheers,
Hao

**Comment by your-diary** [comment]
Now `x_labels(0)` panics.

```
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/plotters-0.3.7/src/coord/ranged1d/types/numeric.rs:246:1:
attempt to multiply with overflow
```
