### ISSUE TITLE
Reversed axis?

### ISSUE THREAD

**Issue by Timmmm** [38/plotters#240]
Is it possible to reverse the axis of a simple graph, so that instead of 1, 2, 3 it goes 3, 2, 1? I couldn't figure it out.

**Comment by 38** [comment]
Hi there,

This is supported if you call `build_cartesian_2d` with reversed range for example `.build_cartesian_2d(3..1, 0..10)` would get x axis reversed.

Closing the issue and feel free to repopen it if anything isn't right.

Thanks!
