### ISSUE TITLE
Can plotters support plot on terminal?

### ISSUE THREAD

**Issue by alienzj** [38/plotters#241]
Hi, Hao,

Can plotters support the plot on the terminal?

I want to plot long reads distribution directly on the terminal. If plotters support this, it would be awesome.

Best regards,
Jie

**Comment by 38** [comment]
Hi Jie,

Sorry for delayed reply - I was not able to actively work on the crate until now. 

There's a text backend see https://github.com/plotters-rs/plotters-text which is WIP. So you probably needs to import the crate from github. Feel to try it. For example.

```rust
use plotters_text::TextDrawingBackend;
use plotters::prelude::*;

let back = TextDrawingBackend::new(70, 30);
let root = back.into_drawing_area();

// Same plotting code goes here
```

Please let me know if you have any question.

Cheers!

**Comment by alienzj** [comment]
Great !
Thanks for your reply.
I will try it.

**Comment by SOF3** [comment]
I want a plotters backend for a TUI framework like [ratatui](https://github.com/ratatui-org/ratatui). Does anyone have similar plans, or should I try working on it?
