### ISSUE TITLE
META: enable GitHub discussions to unclutter the issue tracker from questions

### ISSUE THREAD

**Issue by SirWindfield** [38/plotters#244]
Skimming through the issue tracker a lot of issues are actually questions from users. What do you think about enabling [GitHub discussions](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) and change the issue template to point to the discussions link for questions? :) 

<sub>I really love the library btw :rocket:</sub>

**Comment by 38** [comment]
Great, thanks for letting me know this new feature. Got this enabled already. I was not aware it until I saw your issue. 

Also please don't mind the delayed reply - apologize for not maintaining the repo for a while. 

Cheers!
