### ISSUE TITLE
[BUG] when directory doesn't exist plot silently fails

### ISSUE THREAD

**Issue by vim-zz** [38/plotters#247]
**Describe the bug**
If the path for the plot result does not exists I would expect an error, but there is no such indication.

**To Reproduce**
1. git clone git@github.com:38/plotters.git
2. cd plotters
3. rm -fr plotters-doc-data
4. cargo run --example normal-dist
5. (no png output)

**Version Information**
0.3.0

**Comment by gab-umich** [comment]
Second on this. Very confusing when I tried to setup the example for the first time. 
However, this is already mentioned in #236

**Comment by Wouter-Vokar** [comment]
Also encountered this bug, spent 2 hours trying to figure out what I was doing wrong. Thanks for opening the issue.

**Comment by 38** [comment]
Hi there, thanks for reporting the issue. Actually this problem has a long history, and I am going to close this one as we already have another issue (#236). I will put some more information there, thanks!
