### ISSUE TITLE
is this project dead ?, Do we need to fork it.

### ISSUE THREAD

**Issue by gustav3d** [38/plotters#248]
Even trivial updates like dependency PRs are not happening.

Is current passive situation expected to improve :  
The existing people with commit rights becoming more active, or adding more people ?

**Comment by 38** [comment]
No, but I was not able to maintain it for a while for personal reasons. But now I am able to keep working on it.

**Comment by kellpossible** [comment]
There are still a lot of PRs open without reply comments

**Comment by DaMilyutin** [comment]
@38. if you are not the only mantainer, there are other guys in a team whom you may delegate some abilities. 
Or you could take some participants from community.
