### ISSUE TITLE
[bug] disable_y_axis function does nothing

### ISSUE THREAD

**Issue by AleksLitynski** [38/plotters#250]
The function https://docs.rs/plotters/0.3.0/plotters/chart/struct.MeshStyle.html#method.disable_y_axis doesn't seem to do anything.

This is the code I'm testing with: 

```
use plotters::prelude::*;

fn main() {
    let root = BitMapBackend::new("example.png", (1000, 700))
        .into_drawing_area();

    root.fill(&WHITE).unwrap();

    let mut chart = ChartBuilder::on(&root)
        .set_label_area_size(LabelAreaPosition::Left, 40)
        .set_label_area_size(LabelAreaPosition::Bottom, 40)
        .build_cartesian_2d(0..7, 0..50)
        .unwrap();

    chart.configure_mesh()
        .disable_y_axis()
        .draw().unwrap();

    let data: Vec<(i32, i32)> = vec![
        (0, 10),
        (1, 15),
        (2, 20),
        (3, 25),
        (4, 30),
        (5, 35),
        (6, 40),
    ];

    chart.draw_series(data.iter().map(|(x, y)| {
        let mut bar = Rectangle::new([
            (*x, *y),
            (*x + 1, 0)],
            BLUE.filled());
        bar.set_margin(0, 0, 15, 15);
        bar
    }))
    .unwrap();
}
```

When I call .disable_y_axis, this is the output:
![example](https://user-images.githubusercontent.com/2934890/118498903-779d3900-b6f4-11eb-9fa0-62d6d88172b5.png)

When I comment out .disable_y_axis, this is the output:
![example](https://user-images.githubusercontent.com/2934890/118499010-8edc2680-b6f4-11eb-908b-f92f12f95f12.png)

**Comment by 38** [comment]
Hi there, thanks for using plotters! 

That's a good catch! In fact, `disable_y_axis` has some effect. The first plot doesn't have y axis drawn, however, the value label is still there. This is definitely not expected result. 
I got the fix on master branch and will make it available in next minor release.

Thanks again for the help, cheers!
