### ISSUE TITLE
[Feature Request] `f32` based positioning

### ISSUE THREAD

**Issue by siefkenj** [38/plotters#260]
While data that is graphed can be given as floating points, there are many places where floating point numbers are not accepted. For example, the radius of a circle or the position of text. It would be useful (and is possible in, e.g., SVGs) to allow for sub-pixel positioning, even if those values are quantized before rendering.

It seems like allowing floats everywhere might be a major change, though. And, it would probably break the API in significant ways. How realistic would such a change be?

**Comment by 38** [comment]
Actually this has been discussed for a while. See this issue #128 

One concern is Plotters is back-end agnostic, and for those rasterized back-ends, only integral coordinate make sense. And it's totally possible that some future back-end only have integral coordinate support. 

On the other hand, for SVG back-end, defining a large enough canvas and down scale it when using seems a reasonable workaround.

**Comment by siefkenj** [comment]
Duplicate of #128
