### ISSUE TITLE
[BUG] If the directory is not created, no pictures are generated and no error messages are reported

### ISSUE THREAD

**Issue by lll1412** [38/plotters#262]
https://docs.rs/plotters/0.3.1/plotters/index.html

None of the sample code here produces images when pasted directly, and no error messages are reported, which I found after debugging was caused by the failure to create a directory.

Hopefully it can be fixed to report exception information or to automatically create directories

**Comment by Ragarnoy** [comment]
#236 
I don't understand how this bug is still a thing, it seems pretty critical
