### ISSUE TITLE
Allowing configure the length of the axis

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#31]
Is it possible to divide plot on internally nested charts which have one common X-axis and two different Y-axes? 
Like here:
![chart-sample](https://user-images.githubusercontent.com/10449591/64802812-27bbb580-d594-11e9-9260-600ff77a6399.jpg)

**Comment by serzhiio** [comment]
Great, but can i set the axis to overlay working surface? Now all axes are out of plot.

**Comment by 38** [comment]
You mean the label ? Currently not, but I am going to expose the API allows to adjust the distance from the axis to the label. After that you should able to set the distance to a negative value to make that happen. :)

**Comment by 38** [comment]
Hi @serzhiio , just want to have a follow up on how things going. And I am going to close this issue and create another one tracking the feature that makes the axis inside the plot. 

Feel free to reopen it. And let me know if you have  any other questions. :)

**Comment by serzhiio** [comment]
Do we really need to set y-axis range for partial axis?
`.set_secondary_coord(0..100, make_partial_axis(0f32..10f32, 0.0..0.3).unwrap());`
Seems y-axis is already exists for secondary coord?

**Comment by serzhiio** [comment]
... and how to draw chart using secondary axis?

**Comment by 38** [comment]
> Do we really need to set y-axis range for partial axis?
> `.set_secondary_coord(0..100, make_partial_axis(0f32..10f32, 0.0..0.3).unwrap());`
> Seems y-axis is already exists for secondary coord?

I am not sure what you mean. But this `make_partial_axis` gives you an ability to make an axis which only 30% of the entire range is shown on the axis. 



> ... and how to draw chart using secondary axis?

And for this one, you should be able to use this: https://docs.rs/plotters/0.2.7/plotters/chart/struct.DualCoordChartContext.html#method.draw_secondary_series

**Comment by serzhiio** [comment]
Thx, already managed it.

**Comment by serzhiio** [comment]
With this configuration i cant draw second axis y-labels. They are just not printing out.
```
    let mut chart = ChartBuilder::on(&root_area)
        .x_label_area_size(40)
        .y_label_area_size(40)
        .right_y_label_area_size(40)
        .build_ranged(0..100, 0..100)?
        .set_secondary_coord(0..100, make_partial_axis(0f32..10f32, 0.0..0.3).unwrap());

    chart.configure_mesh().disable_x_mesh().disable_y_mesh().draw()?;
    chart.configure_secondary_axes().y_labels(30).draw()?;
```

**Comment by serzhiio** [comment]
Looks like the problem for is that there is no .label_style() mathod for secondary axes.

**Comment by 38** [comment]
yep, just added in master.
