### ISSUE TITLE
Granular X/Y axis steps

### ISSUE THREAD

**Issue by ernestas-poskus** [38/plotters#34]
Thank you for the crate!

How to configure steps X / Y axis steps to be more granular, e.g.:

![stock image](https://github.com/38/plotters-doc-data/blob/c079ca1e6f5af0f8b9605a7ec3e35de062c17b5f/stock.png?raw=true)

https://github.com/38/plotters/blob/master/examples/stock.rs#L38

First step in X axis: 2019-03-13, last step 2019-04-24, how to force display all 30 dates as steps in this graph?

**Comment by 38** [comment]
Hi, If my understanding is correct you may want to use this API https://docs.rs/plotters/0.2.6/plotters/chart/struct.MeshStyle.html#method.x_labels  which you are changing the maximum number of labels  on x aixs.

**Comment by ernestas-poskus** [comment]
Yes exactly what I need, somehow I have missed these methods :bowing_man:
