### ISSUE TITLE
Drawing very big vectors

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#38]
Lets say i have one very big data vector with stable items array:
`[[datetime, price1, price2, price3],[...][...],...]`
To draw 3 lines with prices:1,2,3 i should iterate over vector 3 times to crate 3 vectors with `[datetime,price1],[datetime,price2],[datetime,price3]`
Would it be more efficient to give a ref on a main vector to plotters and then set 3 accessors funcs to let plotters now how to pull out particular [x;y] for specified chart type;

It could looks like:
```
type DataVectorItem = (datetime_type,price_type,price_type,price_type);
ChartBuilder::on(root)
    .data(&vector)
    .build_ranged(time_start..time_end, min..max).unwrap();
```
```
        chart
            .draw_series(LineSeries::new(
                |data_item:&DataVectorItem| => (x,y) { (data_item.0,data_item.3) }, // accessor func
                &RGBColor(45,140,220).mix(0.9),
            )).unwrap();
```
What you say?

**Comment by 38** [comment]
I think you should be able to do that already.

`LineSeries` takes anything that impls `IntoIterator<Item = Coord>` trait.

https://docs.rs/plotters/0.2.6/plotters/prelude/struct.LineSeries.html

**Comment by serzhiio** [comment]
Great, sorry for noob question.
