### ISSUE TITLE
Setting line width for LineSeries?

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#39]
How can i set line width for LineSeries?

**Comment by 38** [comment]
Stroke width is a newly added feature in 0.2.6

You should be able to use it as following:

```rust
LineSeries::new( ...., Into<ShapeStyle>::into(&RED).stroke_width(2))
```

**Comment by serzhiio** [comment]
```
error[E0277]: the trait bound `plotters::style::ShapeStyle: plotters::style::color::SimpleColor` is not satisfied
   --> src\scenes\instances\components\chart\mod.rs:186:17
    |
186 |                 &Into::<ShapeStyle>::into(&RED).stroke_width(2),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `plotters::style::color::SimpleColor` is not implemented for `plotters::style::ShapeStyle`
    |
    = note: required because of the requirements on the impl of `plotters::style::color::Color` for `plotters::style::ShapeStyle`
    = note: required because of the requirements on the impl of `std::convert::From<&plotters::style::ShapeStyle>` for `plotters::style::ShapeStyle`
    = note: required because of the requirements on the impl of `std::convert::Into<plotters::style::ShapeStyle>` for `&plotters::style::ShapeStyle`
    = note: required by `plotters::series::line_series::LineSeries::<Coord, I>::new`
```

**Comment by 38** [comment]
Remove the leading and sign would fix this.

Cause `&impl Color` can be converted to shape style. as long as you are passing a shape style anyway, you don't need to borrow.

**Comment by serzhiio** [comment]
bingo!

**Comment by serzhiio** [comment]
But in draw_line() func i'm still getting 1!
```
    fn draw_line<S: BackendStyle>(
        &mut self,
        from: BackendCoord,
        to: BackendCoord,
        style: &S,
    ) -> Result<(), DrawingErrorKind<Self::ErrorType>> {
        if style.as_color().alpha() == 0.0 {
            return Ok(());
        }
        let stroke_width = style.stroke_width() as u8;
```

**Comment by serzhiio** [comment]
https://github.com/38/plotters/blob/e0219d9036360f5025f67def237305f03dd5a632/src/drawing/backend.rs#L37

**Comment by 38** [comment]
> But in draw_line() func i'm still getting 1!

Nop, this is the default impelentation

https://github.com/38/plotters/blob/e0219d9036360f5025f67def237305f03dd5a632/src/drawing/backend.rs#L53

This is where it passes through

**Comment by serzhiio** [comment]
I see it, but i cant pull out custom stroke_width from BackendStyle struct.

**Comment by serzhiio** [comment]
Resolved, its working as expected. Sorry for your time.

**Comment by 38** [comment]
No problem. Let me know if you have other questions

**Comment by jbowens** [comment]
I'm having trouble setting a stroke width as well. Does the wasm/canvas backend support setting a stroke width? That's the backend that I've been trying.
