### ISSUE TITLE
[Feature Request] Drawing area split with relative value

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#41]
Ive faced with neccesity to divide drawing area using relative value to canvas size.
Lets say i want to split canvas vertically in proportion 70%/30%.
Or i want lower drawing area to be of a fixed height(200px) but canvas size is dynamically adjusted.
Any advice?

**Comment by 38** [comment]
I have the plan to replace the pixel-based things to a trait that describes the size in general for a long time. But currently Plotters uses the pixel only to specify the dimension. 

For now, the only way to make a relative size is use to compute the number of pixel from your side. 

One helpful API is https://docs.rs/plotters/0.2.6/plotters/drawing/struct.DrawingArea.html#method.dim_in_pixel

You can do stuff like this

```rust
let some_drawing_area = ....;
let (w,h) = some_drawing_area.dim_in_pixel();
let (upper,lower) = some_drawing_area.split_vertically((w as f64 * 0.7) as i32);
```

But I think once the size description trait is added, you will be able to specify the relative size directly.

**Comment by 38** [comment]
Related PR #49 
![image](https://user-images.githubusercontent.com/3023614/66439205-268f7400-e9ec-11e9-9a60-b07e288da5f8.png)
