### ISSUE TITLE
How to get pixel coord from Guest coordinate?

### ISSUE THREAD

**Issue by serzhiio** [38/plotters#48]
Lets say i have chart with given coordinate system.
I need to draw a dotted (horizontal) line through whole chart using one y-coord.
And i want every dot to be 5px length.
What is most efficient way?

**Comment by 38** [comment]
I guess this is what you are looking forhttps://docs.rs/plotters/0.2.7/plotters/drawing/struct.DrawingArea.html

**Comment by serzhiio** [comment]
Why secondary? And how to extract pixel coordinates?

**Comment by 38** [comment]
Oh, I see, I misunderstood what you are trying to do.
You should be able to strip the attached coordinate by using code like that.
```rust
chart.plotting_area().strip_coord_spec()
```
https://docs.rs/plotters/0.2.7/plotters/drawing/struct.DrawingArea.html#method.strip_coord_spec

**Comment by serzhiio** [comment]
IS it possible to draw series on the chart using pixel coordinates?

**Comment by 38** [comment]
Not for now. But I think this may be something worth to add. 

`draw_series` is almost the same as 

```rust
series.for_each(|element| area.draw(element)
```

But if you want to add series annotation for series drawn in this way, it seems very tricky. 
But an API like `draw_pixel_coord_series` which provides ability for further annotation seems a nice idea. 

I don't know if this is what you are asking for ?

**Comment by serzhiio** [comment]
Here is what i looked for:
`let (_, order_y) = price_chart.backend_coord(&(from, (max+min)/2.0));`
