### ISSUE TITLE
[Feature Request] Reduce allocation, reuse backbuffer, improve speed

### ISSUE THREAD

**Issue by ralfbiedert** [38/plotters#54]
### Background

I am using `plotters` together with [minifb](https://github.com/emoon/minifb) to visualize real time sensor data. The combination is awesome, since both libraries are very lightweight, and it's easy to do portable, real-time UIs. 

One implication is that all rendering is purely SW; `plotters` writes into a byte array, which `minifb`  uses to update the frame buffer.

Unfortunately, in that process as of today, data has to be copied around multiple times for no reason other than plumbing, which costs precious CPU cycles. 

### Feature Request

- What is the feature ?

Plotters' `BitMapBackend` should accept a user-provided byte buffer to render into; instead of allocating its own. 

- Why do you need the feature ?
- What is the use case ?

See above; to reduce allocation, improve performance.

**Comment by 38** [comment]
Hi @ralfbiedert, 

Thanks for the suggestion and PR. 
The PR looks great to me and this is definitely the thing needs to be improved!.

Thanks again and I am going to dig into this a little bit and merge the PR!

**Comment by 38** [comment]
Your PR looks really nice and I like it. Seems this issue can be closed, feel free to reopen it if I forget anything. Thanks!
