### ISSUE TITLE
[Feature Request] Should have benchmarks

### ISSUE THREAD

**Issue by ralfbiedert** [38/plotters#57]
- What is the feature ?

After working on #56 and #54 I think it would be nice to have some some reference benchmarks to measure if certain changes actually improve or degrade performance, esp. when iterating the CPU-only `BitMapBackend`.

- Why do you need the feature ?
- What is the use case ?

See above.

**Comment by 38** [comment]
Yes, I saw your benchmark. I believe that is a good start point.

**Comment by ralfbiedert** [comment]
I just saw you implemented criterion benchmarks. Awesome! This is exactly what I was hoping for, thank you so much!
