### ISSUE TITLE
[Feature Request] Improve wasm demo

### ISSUE THREAD

**Issue by TatriX** [38/plotters#67]
I'd like to improve wasm demo a bit. In particular I'd like to move all inline styles to already existing css file, extract js code to a separate file, use es6+ in js code, replace setTimeout with requestAnimationFrame and thus remove double buffering example.
 
Also I'd like to make a realtime rendered demo.
If you think this sounds good, I can start working on that ;)

**Comment by 38** [comment]
Sure that's awesome! I am really appreciate your contribute. Thank you in advance!
