### ISSUE TITLE
[BUG] Typo in plot labels for one of the examples

### ISSUE THREAD

**Issue by torusctyi** [38/plotters#71]
**Description:**
The plot for '1D Gaussian Distribution' has a typo. It actually reads '1D Guassian Distribution'

[The image with the typo can be seen here](https://plotters-rs.github.io/plotters-doc-data/normal-dist2.png)

**Fix:**
The typo is caused by line 25 of the file [plotters/examples/normal-dist2.rs](https://github.com/38/plotters/blob/master/examples/normal-dist2.rs)

**Comment by torusctyi** [comment]
I'm having trouble reproducing the plot on my own machine after downloading it to my own machine. 

I got  `cargo build` and `cargo test` to run fine after downloading necessary dependencies as discussed in [this issue for the Servo project.](https://github.com/servo/libfontconfig/issues/41) (Though [this issue](https://github.com/jwilm/alacritty/issues/1193) was the first result  I found when I googled the first error message  ).

However, running `cargo --example normal-dist2` produces no plot, though the code actually executes.

I then tried downloading the git repository for the documentation. As before, I was able to compile it successfully. But running `cargo run --bin 2_9_vbar` produced no plot as before.

**Comment by 38** [comment]
First, thanks for reporting the typo issue. I was running a type checker for the entire repo. And it fix lot more. 

Also, for the `normal-dist2` example, the file is produced at `plotters-doc-data/normal-dist2.png` 
For the documentation one, it should under `image/2.9.png`.  Just in case you didn't find it. 

If the output is still missing, could you please give me some more details. Is the program crashed or panicked, any error message, etc.

Thanks!

**Comment by torusctyi** [comment]
I found the images files where you said they would be.

**Comment by 38** [comment]
Thanks for the suggestion. Just curios one more thing, do you think if putting your question to the FAQ list would help?

**Comment by torusctyi** [comment]
It'd be a good idea IMHO.

**Comment by 38** [comment]
As long as we are constantly improving the documentation and seems nothing more we can actually do, closing this issue.
