### ISSUE TITLE
Request for one or two more examples of how to use in jupyter

### ISSUE THREAD

**Issue by EdmundsEcho** [38/plotters#8]
This is a great resource.  Thank you.  Being new to Rust, I was looking forward to playing with the language in jupyter.  This lib provides a key ingredient.  This said, I was trying to parse through the example code to draw different charts to no avail.  Do you think you could provide another example or two for me to use to figure out how to use the lib in jupyter?  To be clear, the example you provide, works as promised.  Thank you in advance.  - E

**Comment by 38** [comment]
Sure, I am working on more examples!

**Comment by 38** [comment]
Just let you know I realize having a interactive tutorial in Jupyter may be really helpful and I am currently making it. 

You can check https://raw.githubusercontent.com/38/plotters/jupyter-tutorial/examples/evcxr-jupyter-integration.ipynb for the notebook that is working in progress

**Comment by EdmundsEcho** [comment]
I just tried to click on the link and received "something went wrong" message.  I'll try again this evening.

**Comment by 38** [comment]
I mean you can download this one https://raw.githubusercontent.com/38/plotters-doc-data/master/evcxr-jupyter-integration.ipynb 
And try with your own Jupyter + evcxr.  Yuo can checkout the repo https://github.com/38/plotters-doc-data
And if you have any thoughs, ideas or want to change any thing, you are more than welcome to submit a PR to the data repo (not this one).

Thanks!

**Comment by 38** [comment]
Also check out the static rendered version of this notebook. 

https://plumberserver.com/plotters-docs/evcxr-jupyter-integration.html

**Comment by EdmundsEcho** [comment]
Fantastic.

**Comment by 38** [comment]
I will keep it updated. Now closing the issue
