### ISSUE TITLE
Add support for setting stroke width

### ISSUE THREAD

**Issue by BaeoMaltinsky** [38/plotters#9]
Hello! This is a fantastic crate.

Currently, it seems like it's not possible to configure the stroke width in plotters ([this comment](https://github.com/38/plotters/blob/d214d161bb24878604b7736e384db03b5f3b0670/src/drawing/backend.rs#L34) suggests as much). 

This is a fairly straightforward feature to add to the vector back-ends and I'd be happy to submit a pull request implementing it for piston, svg, and canvas once the API is figured out.

**Comment by 38** [comment]
Yes, that's right. If you are interested in adding it, that would be great.  I can do the API change and after that you are welcome to submit PR! :)

**Comment by 38** [comment]
The stroke width is now supported for most of the case. However, the support isn't complete because the default circle rasterizer doesn't supports stroke width yet. Open another issue to track this one. #40
