### ISSUE TITLE
Move non-default backends into seperate crates

### ISSUE THREAD

**Issue by 38** [38/plotters#96]
# Motivation
Since we got a bunch of backends now, and some backend such as cairo, piston, etc actually actually have a dependency to third-party crates which might be frequently update. 
This increase the maintain burden - we need to keep each depdency such as cairo up-to-dated on crates.io, otherwise it may cause some issue with the people who use the crate. (Especially for cairo, since mostly people will import gtk and cairo directly from their code.) 
But the core code isn't required so many update, so it's better to make them sperate

# What to do?
We should relocate the code such as cairo backend and piston backend to separate crate and make this repo a workplace 
- [ ] Refactor all the blockers
  - [ ] `FontTransform` should be moved to text style, `FontDesc::box_size` should be removed since it's broken with current anchor system
  - [ ] Add trait `BackendFont` as the abstracted font impl, thus backend is not relies on actual font implementation
- [ ] Decouple `drawing::backend` and make it a standalone crate
   - [ ] `RGBAColor`
   - [ ] `TextStyle`
   - [ ] `FontTransform`
   - [ ] `FontStyle`
   - [ ] Default rasterizer
   - [ ] `drawing::backend::*`
- [ ] Update the core crate to use the standalone `plotters-backend` crate
- [ ] Move `PistionBackend` and `CairoBackend` to its own crate (Depdends on `plotters-backend` crate`)

This is considered a breaking change and should ship with 0.3

**Comment by TatriX** [comment]
Sounds goods to me. I'll close linked issue then.

**Comment by 38** [comment]
> Sounds goods to me. I'll close linked issue then.

Sure, the plan is I am going to make a new `plotters-backend` crate which doesn't have any feature option and not coupled with any versions of the core crate. So the backends aren't depdends on any plotters API, thus we won't have the issue with matching backend impls with core crate, as long as the both side uses the same version of `plotters-backend` crate (And hopefully this should be pretty stable and probably update only on major updates).

By doing so both backend crates and core crate can update independently, plus this makes external backends easier to implement.

**Comment by 0b01** [comment]
Awesome. Will this be similar to how imgui-rs handles it's renderer?

**Comment by 38** [comment]
> Awesome. Will this be similar to how imgui-rs handles it's renderer?

Yep, that's basically the plan - But not exactly, I believe we will settled down a better solution which allows third-party backends plug-and-play without touching the core crate.  Another goal for this is I want to avoid versioning hell issue in the future - as more and more backend is added. Which I believe image-rs doesn't have a good way to dealing with currently (e.g. If you want to import your version of say gif crate)

**Comment by 38** [comment]
Closed by PR #103
