### ISSUE TITLE
[BUG] Piston Example misses LineSeries

### ISSUE THREAD

**Issue by AiyionPrime** [38/plotters#97]
**Describe the bug**
After cloning plotters to a ne wdirectory in /tmp and building it with 'cargo build',
I changed into the example directory for piston and running it, it complains of being unable to find "LineSeries".

**To Reproduce**

`cd /tmp`
`git clone https://github.com/38/plotters.git`
`cd plotters`
`cargo build`
`cd examples/piston-demo`
`cargo run --release`

**Version Information**
For now I'm pulling plotters from master;
I'll try to build the example from the lates release on crates.io as next, but doubt it'll chnage the outcome to the better.

**Comment by AiyionPrime** [comment]
Might be related to #30, which does not mention LineSeries, but is still open.

**Comment by AiyionPrime** [comment]
I just tried, creating a new crate, pasting the piston example, and using plotters by it's latest version insted of by a given path results in the same error about "draw_piston_window()",  which @bermeon found earlier.

**Comment by 38** [comment]
Hello, thanks for reporting this. 
I believe this is unrelated to issue #30, and the cause should be the example is out-of-dated after we add the feature that allows different components opt in and out. 

Just add line series to its `Cargo.tmol` should work.  Believe it's fixed on master now. 

Thanks for the help,
Cheers

**Comment by AiyionPrime** [comment]
I just verified it using the master branch; adding the line in the toml resolves the issue.
Thanks for the effort, this helps me a lot to gain a foothold in rust and gui design.
However, I wish you happy Christmas holidays!
