### ISSUE TITLE
[Feature Request] Bar Graphs

### ISSUE THREAD

**Issue by caemor** [38/plotters#98]
### What is the feature ?

Add support for bar graphs which are similar to histograms but slightly different ;-)

Examples for bar graphs:

![image](https://user-images.githubusercontent.com/11088935/71981203-263c8a00-3222-11ea-9774-6d65f9a6b92a.png) 

(image from https://www.mathsisfun.com/data/bar-graphs.html)

or 
![image](https://user-images.githubusercontent.com/11088935/71981136-07d68e80-3222-11ea-97e4-5e30eeca1ef5.png)

### (Optional) Why this feature is useful and how people would use the feature ?

It's similar to histograms but is more focused on categories/... and doesn't only work for continous data.

**Comment by 38** [comment]
Hi there, thanks for the feature request. If my understanding is correct, the feature is already supported by Plotters. 

Plotters is actually a drawing library that makes plotting easier, which means it doesn't limits you on predefined plot types. In general, we abstract a series as a iterator of drawable elements. 

Thus the feature can be supported by passing an iterator of rectangles to `ChartContext::draw_series`. 

I am documenting all those stuff (but very slowly). And this may be more detailed answer to how to draw the chart. [https://plotters-rs.github.io/book/basic/basic_data_plotting.html#histogram]( https://plotters-rs.github.io/book/basic/basic_data_plotting.html#histogram )

**Comment by caemor** [comment]
Thanks for your response :-)
I already tried it with the histogram type yesterday but I wasn't able to either add specific labels to each rectangle (so I wouldn't need any floats) or to use float values in my histogram. So it's more a program to label my data correctly (or alternatively to draw it on the correct position of the diagram. But maybe I tried it the wrong way and would be happy to get some pointers if this is already possible with the current version.

**Comment by matiu2** [comment]
I too would like to draw bar graphs. My X axis is a Category axis with values (in days): **<1, 1-3, 3-6, 6-9 days, >9 days**

I've spent almost a whole day trying to figure out how to do it. I think I want to use a **plotters::coord::Category** but Histogram's don't support that because it doesn't implement **plotters::coord::DiscreteRanged**

And of course I can't implement it in my own code; I'll try hacking the source..

**Comment by matiu2** [comment]
Sorry I found a bug and force pushed.

It's still not working 100% for me; I'm getting an extra column on the left, and I have no idea why :(

All help appreciated.

![image](https://user-images.githubusercontent.com/790456/74341023-c9b92580-4df2-11ea-9b16-3a8eb9b1ede6.png)

**Comment by 38** [comment]
I suppose this is already supported by v0.3 when using slice as coord spec, so closing the issue
